### ISSUE TITLE
Map start

### ISSUE THREAD

**Issue by nine007** [osmandapp/web#395]
Good day

When I want to start the map I get the following error:

OK. File 'src/resources/generated/online-routing-providers.json' generated successfully (1196 bytes)
Error: ENOTDIR: not a directory, scandir 'C:\web\map\public\images\poi-icons-svg'
    at readdirSync (node:fs:1509:26)
    at ls (file:///C:/web/map/src/resources/scripts/generate-resources.mjs:88:16)
    at file:///C:/web/map/src/resources/scripts/generate-resources.mjs:18:11
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:474:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:119:5) {
  errno: -4052,
  code: 'ENOTDIR',
  syscall: 'scandir',
  path: 'C:\\web\\map\\public\\images\\poi-icons-svg'
}
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at cat (file:///C:/web/map/src/resources/scripts/generate-resources.mjs:99:21)
    at generate (file:///C:/web/map/src/resources/scripts/generate-resources.mjs:68:23)
    at file:///C:/web/map/src/resources/scripts/generate-resources.mjs:16:1
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:474:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:119:5)
file:///C:/web/map/src/resources/scripts/generate-resources.mjs:79
    throw new Error(`Fatal error: ${file} neither found nor generated`);
          ^

Error: Fatal error: src/resources/generated/poiicons.json neither found nor generated
    at generate (file:///C:/web/map/src/resources/scripts/generate-resources.mjs:79:11)
    at file:///C:/web/map/src/resources/scripts/generate-resources.mjs:16:1
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:474:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:119:5)

Any solution to this?
thank you

**Comment by DmitryAlexei** [comment]
You need to put osmand resources by the provided links

**Comment by nine007** [comment]
Thank you for your feedback, but can you give me more details please?
thank you
