### ISSUE TITLE
Crash when tapping to a waypoint from the list

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/web#445]
## Steps of reproduce
1. Create a track with waypoints 
[Mon Jul 29 2024 - 2.gpx.zip](https://github.com/user-attachments/files/16409666/Mon.Jul.29.2024.-.2.gpx.zip)

created 3 waypoints, but there are 2 waypoints on the list.

2. click to any waypoints from this list or on the map

![telegram-cloud-photo-size-2-5276436463975785172-y](https://github.com/user-attachments/assets/4777726e-3fd1-4d79-a0d0-6af0e74a5af7)

3. crash:

react-dom.production.min.js:189 TypeError: x.latlon.lat.toFixed is not a function
    at hce (WptDetails.jsx:645:63)
    at Sa (react-dom.production.min.js:167:137)
    at As (react-dom.production.min.js:197:258)
    at Sl (react-dom.production.min.js:292:88)
    at bc (react-dom.production.min.js:280:389)
    at vc (react-dom.production.min.js:280:320)
    at fc (react-dom.production.min.js:280:180)
    at ac (react-dom.production.min.js:271:88)
    at rc (react-dom.production.min.js:268:429)
    at w (scheduler.production.min.js:13:203)
ps @ react-dom.production.min.js:189
n.callback @ react-dom.production.min.js:189
Fr @ react-dom.production.min.js:144
xl @ react-dom.production.min.js:262
bl @ react-dom.production.min.js:260
yl @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
wc @ react-dom.production.min.js:281
rc @ react-dom.production.min.js:270
w @ scheduler.production.min.js:13
P @ scheduler.production.min.js:14
Show 11 more frames
Show less
WptDetails.jsx:645 Uncaught TypeError: x.latlon.lat.toFixed is not a function
    at hce (WptDetails.jsx:645:63)
    at Sa (react-dom.production.min.js:167:137)
    at As (react-dom.production.min.js:197:258)
    at Sl (react-dom.production.min.js:292:88)
    at bc (react-dom.production.min.js:280:389)
    at vc (react-dom.production.min.js:280:320)
    at fc (react-dom.production.min.js:280:180)
    at ac (react-dom.production.min.js:271:88)
    at rc (react-dom.production.min.js:268:429)
    at w (scheduler.production.min.js:13:203)

![telegram-cloud-photo-size-2-5276436463975785173-y](https://github.com/user-attachments/assets/59b40a90-15f9-46dd-aa4f-a88982ceede1)

**Comment by alisa911** [comment]
- [ ] fix wpt tab (add new wpt)
- [ ] fix crash with latlon
- [ ] fix click on wpt when editing track
- [ ] fix loading address for wpt info
- [ ] fix crash in gallery
