### ISSUE TITLE
Store user login session after updates

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/web#585]
## Description
Every time the development team updates the main/production version of osmand.net, users are required to log in again. 
This disrupts the user experience and can be quite frustrating. Is there a way to preserve user sessions across updates or, alternatively, reduce the frequency of updates on the main site?

**Comment by vshcherb** [comment]
Better to use redis like db with expired row  than postgresql

**Comment by RZR-UA** [comment]
Redis-related crash (admin area) to fix:

```
Caused by: org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.io.NotSerializableException: net.osmand.server.api.repo.DeviceSubscriptionsRepository$SupporterDeviceSubscription
        at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:64)
        at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:33)
        at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.serialize(JdkSerializationRedisSerializer.java:94)
        at org.springframework.data.redis.core.AbstractOperations.rawHashValue(AbstractOperations.java:186)
        at org.springframework.data.redis.core.DefaultHashOperations.putAll(DefaultHashOperations.java:209)
        at org.springframework.data.redis.core.DefaultBoundHashOperations.putAll(DefaultBoundHashOperations.java:187)
        at org.springframework.session.data.redis.RedisIndexedSessionRepository$RedisSession.saveDelta(RedisIndexedSessionRepository.java:811)
        at org.springframework.session.data.redis.RedisIndexedSessionRepository$RedisSession.save(RedisIndexedSessionRepository.java:799)
        at org.springframework.session.data.redis.RedisIndexedSessionRepository$RedisSession.access$000(RedisIndexedSessionRepository.java:686)
        at org.springframework.session.data.redis.RedisIndexedSessionRepository.save(RedisIndexedSessionRepository.java:415)
```

**Comment by RZR-UA** [comment]
Redis is back. @alisa911, please add serialVersionUID to all other Repositories.
